-- V1: 우리 7개 OTT 서비스 마스터(ERD ott_service)와 시드 (Task 019)
-- TMDB provider_id 매핑은 tmdb_provider(Task 033)에서 다룬다. 이 테이블에는 넣지 않는다.

CREATE TABLE ott_service (
	id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	code          VARCHAR(30)  NOT NULL,                  -- NETFLIX 등 서비스 코드
	name          VARCHAR(50)  NOT NULL,                  -- 화면 표시 이름
	logo_path     VARCHAR(200) NOT NULL,                  -- TMDB 이미지 상대 경로. URL 조립은 프론트가 한다
	display_order INT          NOT NULL,                  -- 화면 정렬 순서
	data_quality  VARCHAR(20)  NOT NULL,                  -- NORMAL / INSUFFICIENT
	created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
	updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
	CONSTRAINT uk_ott_service_code UNIQUE (code)
);

-- id를 지정하지 않고 정렬 순서대로 넣어 새 DB에서 1~7을 받는다(직접 지정하면 IDENTITY 시퀀스가 앞으로 가지 않는다)
-- 왓챠 로고는 TMDB에 남아 있는 왓챠플레이 시절 구버전이다. 바꾸려면 이 파일이 아니라 새 마이그레이션을 추가한다.
-- 쿠팡플레이는 TMDB 데이터가 부족해 INSUFFICIENT로 둔다.
INSERT INTO ott_service (code, name, logo_path, display_order, data_quality) VALUES
	('NETFLIX',       '넷플릭스',   '/rK1KljqmbvO9HQa1PBFLILWah72.png', 1, 'NORMAL'),
	('DISNEY_PLUS',   '디즈니+',    '/5eZ872CghnHFLB1j8grszbrx0dx.png', 2, 'NORMAL'),
	('APPLE_TV_PLUS', '애플 TV+',   '/9icYBfYFcwgCbky5VdGUIKJ4C5i.png', 3, 'NORMAL'),
	('TVING',         '티빙',       '/w4ov8Zx73eu2TjHsDs5EmiuYKA4.png', 4, 'NORMAL'),
	('WAVVE',         '웨이브',     '/mh1vBeclG7Eq15TjRnmyustqp3v.png', 5, 'NORMAL'),
	('WATCHA',        '왓챠',       '/ppQIS7UMtBwJSspSoGqDR8wO1Gr.png', 6, 'NORMAL'),
	('COUPANG_PLAY',  '쿠팡플레이', '/bP0TPAhxmSdIthEWbzdI1NQB4C2.png', 7, 'INSUFFICIENT');
